# Generated by Django 5.1.1 on 2024-10-05 07:32

import contents.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('name', models.CharField(max_length=300)),
            ],
            bases=(models.Model, contents.models.ModelWithTimeStamp),
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_code', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            bases=(models.Model, contents.models.ModelWithTimeStamp),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=(models.Model, contents.models.ModelWithTimeStamp),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_category', models.CharField(max_length=100)),
                ('product_subcategory', models.CharField(max_length=100)),
                ('product_brand', models.CharField(max_length=100)),
                ('product_stock', models.IntegerField()),
            ],
            bases=(models.Model, contents.models.ModelWithTimeStamp),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_contact_name', models.CharField(max_length=255)),
                ('supplier_email', models.EmailField(max_length=254)),
                ('supplier_phone', models.CharField(max_length=20)),
            ],
            bases=(models.Model, contents.models.ModelWithTimeStamp),
        ),
        migrations.AlterField(
            model_name='author',
            name='unique_id',
            field=models.CharField(default=uuid.uuid4, max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='unique_id',
            field=models.CharField(default=uuid.uuid4, max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('order_status', models.CharField(max_length=50)),
                ('shipping_method', models.CharField(max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.payment')),
            ],
            bases=(models.Model, contents.models.ModelWithTimeStamp),
        ),
        migrations.CreateModel(
            name='OrderItemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('marketing_campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.marketingcampaign')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.product')),
            ],
            bases=(models.Model, contents.models.ModelWithTimeStamp),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='contents.OrderItemInfo', to='contents.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.supplier'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(max_length=255)),
                ('shelf_number', models.CharField(max_length=50)),
                ('reorder_point', models.IntegerField()),
                ('warehouse_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.address')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.supplier')),
            ],
            bases=(models.Model, contents.models.ModelWithTimeStamp),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.address')),
                ('wishlist', models.ManyToManyField(to='contents.product')),
            ],
            bases=(models.Model, contents.models.ModelWithTimeStamp),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(blank=True, null=True)),
                ('review_rating', models.IntegerField(blank=True, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.product')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.userinfo')),
            ],
            bases=(models.Model, contents.models.ModelWithTimeStamp),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.userinfo'),
        ),
        migrations.CreateModel(
            name='CustomerServiceTicket',
            fields=[
                ('support_ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('support_ticket_status', models.CharField(blank=True, max_length=50, null=True)),
                ('support_agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.userinfo')),
            ],
            bases=(models.Model, contents.models.ModelWithTimeStamp),
        ),
    ]
